dbrl1 = dbrl(normData, noise1)
    # dbrl2 = dbrl(normData, noise2)
    # dbrl3 = dbrl(normData, noise3)
    # dbrl4 = dbrl(normData, noise4)
    # dbrl5 = dbrl(normData, noise5)
    # dbrl6 = dbrl(normData, noise6)

    # #print("Euclidean distance between two said series: ", euclideanDist)

    # infoLoss1 = infoLoss(normData, noise1)
    # infoLoss2 = infoLoss(normData, noise2)
    # infoLoss3 = infoLoss(normData, noise3)
    # infoLoss4 = infoLoss(normData, noise4)
    # infoLoss5 = infoLoss(normData, noise5)
    # infoLoss6 = infoLoss(normData, noise6)